# Generated by Django 2.1 on 2019-01-18 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_published']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Hostel',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
